# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop


jobs:
- job: TestUbuntu
  displayName: 'Test Ubuntu Latest'

  pool:
    vmImage: ubuntu-latest

  steps:
  - script: |
      echo "Install dependencies"
      chmod +x ./.ci/install.sh
      ./.ci/install.sh
    displayName: 'Install dependencies'

  - script: |
      echo "Build dependencies"
      chmod +x ./.ci/build.sh
      ./.ci/build.sh
    displayName: 'Build codebase'

  - script: |
      echo "Running test"
      ./build/test/QuixStreaming_tst
    displayName: 'Run test'
