// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parameterDefinitionsProto.proto

#include "parameterDefinitionsProto.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Quix {
namespace Process {
constexpr ParameterDefinitionProto::ParameterDefinitionProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , location_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , _oneof_case_{}{}
struct ParameterDefinitionProtoDefaultTypeInternal {
  constexpr ParameterDefinitionProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ParameterDefinitionProtoDefaultTypeInternal() {}
  union {
    ParameterDefinitionProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ParameterDefinitionProtoDefaultTypeInternal _ParameterDefinitionProto_default_instance_;
constexpr ParameterDefinitionsProto::ParameterDefinitionsProto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : parameters_(){}
struct ParameterDefinitionsProtoDefaultTypeInternal {
  constexpr ParameterDefinitionsProtoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ParameterDefinitionsProtoDefaultTypeInternal() {}
  union {
    ParameterDefinitionsProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ParameterDefinitionsProtoDefaultTypeInternal _ParameterDefinitionsProto_default_instance_;
}  // namespace Process
}  // namespace Quix
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_parameterDefinitionsProto_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_parameterDefinitionsProto_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_parameterDefinitionsProto_2eproto = nullptr;

const uint32_t TableStruct_parameterDefinitionsProto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, id_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, location_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, name_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, description_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, minimumValue_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, maximumValue_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, unit_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, format_),
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionProto, customProperties_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionsProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Quix::Process::ParameterDefinitionsProto, parameters_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Quix::Process::ParameterDefinitionProto)},
  { 29, -1, -1, sizeof(::Quix::Process::ParameterDefinitionsProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Quix::Process::_ParameterDefinitionProto_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Quix::Process::_ParameterDefinitionsProto_default_instance_),
};

const char descriptor_table_protodef_parameterDefinitionsProto_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037parameterDefinitionsProto.proto\022\014Quix."
  "Process\"\214\004\n\030ParameterDefinitionProto\022\n\n\002"
  "id\030\001 \001(\t\022\023\n\tname_null\030\002 \001(\010H\000\022\024\n\nname_va"
  "lue\030\003 \001(\tH\000\022\032\n\020description_null\030\004 \001(\010H\001\022"
  "\033\n\021description_value\030\005 \001(\tH\001\022\033\n\021minimumV"
  "alue_null\030\006 \001(\010H\002\022\034\n\022minimumValue_value\030"
  "\007 \001(\001H\002\022\033\n\021maximumValue_null\030\010 \001(\010H\003\022\034\n\022"
  "maximumValue_value\030\t \001(\001H\003\022\023\n\tunit_null\030"
  "\n \001(\010H\004\022\024\n\nunit_value\030\013 \001(\tH\004\022\025\n\013format_"
  "null\030\014 \001(\010H\005\022\026\n\014format_value\030\r \001(\tH\005\022\037\n\025"
  "customProperties_null\030\016 \001(\010H\006\022 \n\026customP"
  "roperties_value\030\017 \001(\tH\006\022\020\n\010location\030\020 \001("
  "\tB\006\n\004nameB\r\n\013descriptionB\016\n\014minimumValue"
  "B\016\n\014maximumValueB\006\n\004unitB\010\n\006formatB\022\n\020cu"
  "stomProperties\"W\n\031ParameterDefinitionsPr"
  "oto\022:\n\nparameters\030\001 \003(\0132&.Quix.Process.P"
  "arameterDefinitionProtoB!\252\002\036Quix.Sdk.Pro"
  "cess.Models.Codecsb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_parameterDefinitionsProto_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_parameterDefinitionsProto_2eproto = {
  false, false, 706, descriptor_table_protodef_parameterDefinitionsProto_2eproto, "parameterDefinitionsProto.proto", 
  &descriptor_table_parameterDefinitionsProto_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_parameterDefinitionsProto_2eproto::offsets,
  file_level_metadata_parameterDefinitionsProto_2eproto, file_level_enum_descriptors_parameterDefinitionsProto_2eproto, file_level_service_descriptors_parameterDefinitionsProto_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_parameterDefinitionsProto_2eproto_getter() {
  return &descriptor_table_parameterDefinitionsProto_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_parameterDefinitionsProto_2eproto(&descriptor_table_parameterDefinitionsProto_2eproto);
namespace Quix {
namespace Process {

// ===================================================================

class ParameterDefinitionProto::_Internal {
 public:
};

ParameterDefinitionProto::ParameterDefinitionProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:Quix.Process.ParameterDefinitionProto)
}
ParameterDefinitionProto::ParameterDefinitionProto(const ParameterDefinitionProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArenaForAllocation());
  }
  location_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    location_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_location().empty()) {
    location_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_location(), 
      GetArenaForAllocation());
  }
  clear_has_name();
  switch (from.name_case()) {
    case kNameNull: {
      _internal_set_name_null(from._internal_name_null());
      break;
    }
    case kNameValue: {
      _internal_set_name_value(from._internal_name_value());
      break;
    }
    case NAME_NOT_SET: {
      break;
    }
  }
  clear_has_description();
  switch (from.description_case()) {
    case kDescriptionNull: {
      _internal_set_description_null(from._internal_description_null());
      break;
    }
    case kDescriptionValue: {
      _internal_set_description_value(from._internal_description_value());
      break;
    }
    case DESCRIPTION_NOT_SET: {
      break;
    }
  }
  clear_has_minimumValue();
  switch (from.minimumValue_case()) {
    case kMinimumValueNull: {
      _internal_set_minimumvalue_null(from._internal_minimumvalue_null());
      break;
    }
    case kMinimumValueValue: {
      _internal_set_minimumvalue_value(from._internal_minimumvalue_value());
      break;
    }
    case MINIMUMVALUE_NOT_SET: {
      break;
    }
  }
  clear_has_maximumValue();
  switch (from.maximumValue_case()) {
    case kMaximumValueNull: {
      _internal_set_maximumvalue_null(from._internal_maximumvalue_null());
      break;
    }
    case kMaximumValueValue: {
      _internal_set_maximumvalue_value(from._internal_maximumvalue_value());
      break;
    }
    case MAXIMUMVALUE_NOT_SET: {
      break;
    }
  }
  clear_has_unit();
  switch (from.unit_case()) {
    case kUnitNull: {
      _internal_set_unit_null(from._internal_unit_null());
      break;
    }
    case kUnitValue: {
      _internal_set_unit_value(from._internal_unit_value());
      break;
    }
    case UNIT_NOT_SET: {
      break;
    }
  }
  clear_has_format();
  switch (from.format_case()) {
    case kFormatNull: {
      _internal_set_format_null(from._internal_format_null());
      break;
    }
    case kFormatValue: {
      _internal_set_format_value(from._internal_format_value());
      break;
    }
    case FORMAT_NOT_SET: {
      break;
    }
  }
  clear_has_customProperties();
  switch (from.customProperties_case()) {
    case kCustomPropertiesNull: {
      _internal_set_customproperties_null(from._internal_customproperties_null());
      break;
    }
    case kCustomPropertiesValue: {
      _internal_set_customproperties_value(from._internal_customproperties_value());
      break;
    }
    case CUSTOMPROPERTIES_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Quix.Process.ParameterDefinitionProto)
}

inline void ParameterDefinitionProto::SharedCtor() {
id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
location_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  location_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
clear_has_name();
clear_has_description();
clear_has_minimumValue();
clear_has_maximumValue();
clear_has_unit();
clear_has_format();
clear_has_customProperties();
}

ParameterDefinitionProto::~ParameterDefinitionProto() {
  // @@protoc_insertion_point(destructor:Quix.Process.ParameterDefinitionProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ParameterDefinitionProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  location_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (has_name()) {
    clear_name();
  }
  if (has_description()) {
    clear_description();
  }
  if (has_minimumValue()) {
    clear_minimumValue();
  }
  if (has_maximumValue()) {
    clear_maximumValue();
  }
  if (has_unit()) {
    clear_unit();
  }
  if (has_format()) {
    clear_format();
  }
  if (has_customProperties()) {
    clear_customProperties();
  }
}

void ParameterDefinitionProto::ArenaDtor(void* object) {
  ParameterDefinitionProto* _this = reinterpret_cast< ParameterDefinitionProto* >(object);
  (void)_this;
}
void ParameterDefinitionProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ParameterDefinitionProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ParameterDefinitionProto::clear_name() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (name_case()) {
    case kNameNull: {
      // No need to clear
      break;
    }
    case kNameValue: {
      name_.name_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case NAME_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = NAME_NOT_SET;
}

void ParameterDefinitionProto::clear_description() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (description_case()) {
    case kDescriptionNull: {
      // No need to clear
      break;
    }
    case kDescriptionValue: {
      description_.description_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case DESCRIPTION_NOT_SET: {
      break;
    }
  }
  _oneof_case_[1] = DESCRIPTION_NOT_SET;
}

void ParameterDefinitionProto::clear_minimumValue() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (minimumValue_case()) {
    case kMinimumValueNull: {
      // No need to clear
      break;
    }
    case kMinimumValueValue: {
      // No need to clear
      break;
    }
    case MINIMUMVALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[2] = MINIMUMVALUE_NOT_SET;
}

void ParameterDefinitionProto::clear_maximumValue() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (maximumValue_case()) {
    case kMaximumValueNull: {
      // No need to clear
      break;
    }
    case kMaximumValueValue: {
      // No need to clear
      break;
    }
    case MAXIMUMVALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[3] = MAXIMUMVALUE_NOT_SET;
}

void ParameterDefinitionProto::clear_unit() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (unit_case()) {
    case kUnitNull: {
      // No need to clear
      break;
    }
    case kUnitValue: {
      unit_.unit_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case UNIT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[4] = UNIT_NOT_SET;
}

void ParameterDefinitionProto::clear_format() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (format_case()) {
    case kFormatNull: {
      // No need to clear
      break;
    }
    case kFormatValue: {
      format_.format_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case FORMAT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[5] = FORMAT_NOT_SET;
}

void ParameterDefinitionProto::clear_customProperties() {
// @@protoc_insertion_point(one_of_clear_start:Quix.Process.ParameterDefinitionProto)
  switch (customProperties_case()) {
    case kCustomPropertiesNull: {
      // No need to clear
      break;
    }
    case kCustomPropertiesValue: {
      customProperties_.customproperties_value_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
      break;
    }
    case CUSTOMPROPERTIES_NOT_SET: {
      break;
    }
  }
  _oneof_case_[6] = CUSTOMPROPERTIES_NOT_SET;
}


void ParameterDefinitionProto::Clear() {
// @@protoc_insertion_point(message_clear_start:Quix.Process.ParameterDefinitionProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_.ClearToEmpty();
  location_.ClearToEmpty();
  clear_name();
  clear_description();
  clear_minimumValue();
  clear_maximumValue();
  clear_unit();
  clear_format();
  clear_customProperties();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParameterDefinitionProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.id"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool name_null = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _internal_set_name_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_name_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.name_value"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool description_null = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _internal_set_description_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string description_value = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_description_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.description_value"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool minimumValue_null = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _internal_set_minimumvalue_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double minimumValue_value = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _internal_set_minimumvalue_value(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bool maximumValue_null = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _internal_set_maximumvalue_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double maximumValue_value = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _internal_set_maximumvalue_value(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bool unit_null = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _internal_set_unit_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string unit_value = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_unit_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.unit_value"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool format_null = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _internal_set_format_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string format_value = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_format_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.format_value"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool customProperties_null = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _internal_set_customproperties_null(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string customProperties_value = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_customproperties_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.customProperties_value"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string location = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          auto str = _internal_mutable_location();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Quix.Process.ParameterDefinitionProto.location"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ParameterDefinitionProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Quix.Process.ParameterDefinitionProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // bool name_null = 2;
  if (_internal_has_name_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_name_null(), target);
  }

  // string name_value = 3;
  if (_internal_has_name_value()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name_value().data(), static_cast<int>(this->_internal_name_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.name_value");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_name_value(), target);
  }

  // bool description_null = 4;
  if (_internal_has_description_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_description_null(), target);
  }

  // string description_value = 5;
  if (_internal_has_description_value()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description_value().data(), static_cast<int>(this->_internal_description_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.description_value");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_description_value(), target);
  }

  // bool minimumValue_null = 6;
  if (_internal_has_minimumvalue_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_minimumvalue_null(), target);
  }

  // double minimumValue_value = 7;
  if (_internal_has_minimumvalue_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_minimumvalue_value(), target);
  }

  // bool maximumValue_null = 8;
  if (_internal_has_maximumvalue_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(8, this->_internal_maximumvalue_null(), target);
  }

  // double maximumValue_value = 9;
  if (_internal_has_maximumvalue_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(9, this->_internal_maximumvalue_value(), target);
  }

  // bool unit_null = 10;
  if (_internal_has_unit_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(10, this->_internal_unit_null(), target);
  }

  // string unit_value = 11;
  if (_internal_has_unit_value()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_unit_value().data(), static_cast<int>(this->_internal_unit_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.unit_value");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_unit_value(), target);
  }

  // bool format_null = 12;
  if (_internal_has_format_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(12, this->_internal_format_null(), target);
  }

  // string format_value = 13;
  if (_internal_has_format_value()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_format_value().data(), static_cast<int>(this->_internal_format_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.format_value");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_format_value(), target);
  }

  // bool customProperties_null = 14;
  if (_internal_has_customproperties_null()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(14, this->_internal_customproperties_null(), target);
  }

  // string customProperties_value = 15;
  if (_internal_has_customproperties_value()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_customproperties_value().data(), static_cast<int>(this->_internal_customproperties_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.customProperties_value");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_customproperties_value(), target);
  }

  // string location = 16;
  if (!this->_internal_location().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_location().data(), static_cast<int>(this->_internal_location().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Quix.Process.ParameterDefinitionProto.location");
    target = stream->WriteStringMaybeAliased(
        16, this->_internal_location(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Quix.Process.ParameterDefinitionProto)
  return target;
}

size_t ParameterDefinitionProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Quix.Process.ParameterDefinitionProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string location = 16;
  if (!this->_internal_location().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_location());
  }

  switch (name_case()) {
    // bool name_null = 2;
    case kNameNull: {
      total_size += 1 + 1;
      break;
    }
    // string name_value = 3;
    case kNameValue: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name_value());
      break;
    }
    case NAME_NOT_SET: {
      break;
    }
  }
  switch (description_case()) {
    // bool description_null = 4;
    case kDescriptionNull: {
      total_size += 1 + 1;
      break;
    }
    // string description_value = 5;
    case kDescriptionValue: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_description_value());
      break;
    }
    case DESCRIPTION_NOT_SET: {
      break;
    }
  }
  switch (minimumValue_case()) {
    // bool minimumValue_null = 6;
    case kMinimumValueNull: {
      total_size += 1 + 1;
      break;
    }
    // double minimumValue_value = 7;
    case kMinimumValueValue: {
      total_size += 1 + 8;
      break;
    }
    case MINIMUMVALUE_NOT_SET: {
      break;
    }
  }
  switch (maximumValue_case()) {
    // bool maximumValue_null = 8;
    case kMaximumValueNull: {
      total_size += 1 + 1;
      break;
    }
    // double maximumValue_value = 9;
    case kMaximumValueValue: {
      total_size += 1 + 8;
      break;
    }
    case MAXIMUMVALUE_NOT_SET: {
      break;
    }
  }
  switch (unit_case()) {
    // bool unit_null = 10;
    case kUnitNull: {
      total_size += 1 + 1;
      break;
    }
    // string unit_value = 11;
    case kUnitValue: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_unit_value());
      break;
    }
    case UNIT_NOT_SET: {
      break;
    }
  }
  switch (format_case()) {
    // bool format_null = 12;
    case kFormatNull: {
      total_size += 1 + 1;
      break;
    }
    // string format_value = 13;
    case kFormatValue: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_format_value());
      break;
    }
    case FORMAT_NOT_SET: {
      break;
    }
  }
  switch (customProperties_case()) {
    // bool customProperties_null = 14;
    case kCustomPropertiesNull: {
      total_size += 1 + 1;
      break;
    }
    // string customProperties_value = 15;
    case kCustomPropertiesValue: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_customproperties_value());
      break;
    }
    case CUSTOMPROPERTIES_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ParameterDefinitionProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ParameterDefinitionProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ParameterDefinitionProto::GetClassData() const { return &_class_data_; }

void ParameterDefinitionProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ParameterDefinitionProto *>(to)->MergeFrom(
      static_cast<const ParameterDefinitionProto &>(from));
}


void ParameterDefinitionProto::MergeFrom(const ParameterDefinitionProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Quix.Process.ParameterDefinitionProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _internal_set_id(from._internal_id());
  }
  if (!from._internal_location().empty()) {
    _internal_set_location(from._internal_location());
  }
  switch (from.name_case()) {
    case kNameNull: {
      _internal_set_name_null(from._internal_name_null());
      break;
    }
    case kNameValue: {
      _internal_set_name_value(from._internal_name_value());
      break;
    }
    case NAME_NOT_SET: {
      break;
    }
  }
  switch (from.description_case()) {
    case kDescriptionNull: {
      _internal_set_description_null(from._internal_description_null());
      break;
    }
    case kDescriptionValue: {
      _internal_set_description_value(from._internal_description_value());
      break;
    }
    case DESCRIPTION_NOT_SET: {
      break;
    }
  }
  switch (from.minimumValue_case()) {
    case kMinimumValueNull: {
      _internal_set_minimumvalue_null(from._internal_minimumvalue_null());
      break;
    }
    case kMinimumValueValue: {
      _internal_set_minimumvalue_value(from._internal_minimumvalue_value());
      break;
    }
    case MINIMUMVALUE_NOT_SET: {
      break;
    }
  }
  switch (from.maximumValue_case()) {
    case kMaximumValueNull: {
      _internal_set_maximumvalue_null(from._internal_maximumvalue_null());
      break;
    }
    case kMaximumValueValue: {
      _internal_set_maximumvalue_value(from._internal_maximumvalue_value());
      break;
    }
    case MAXIMUMVALUE_NOT_SET: {
      break;
    }
  }
  switch (from.unit_case()) {
    case kUnitNull: {
      _internal_set_unit_null(from._internal_unit_null());
      break;
    }
    case kUnitValue: {
      _internal_set_unit_value(from._internal_unit_value());
      break;
    }
    case UNIT_NOT_SET: {
      break;
    }
  }
  switch (from.format_case()) {
    case kFormatNull: {
      _internal_set_format_null(from._internal_format_null());
      break;
    }
    case kFormatValue: {
      _internal_set_format_value(from._internal_format_value());
      break;
    }
    case FORMAT_NOT_SET: {
      break;
    }
  }
  switch (from.customProperties_case()) {
    case kCustomPropertiesNull: {
      _internal_set_customproperties_null(from._internal_customproperties_null());
      break;
    }
    case kCustomPropertiesValue: {
      _internal_set_customproperties_value(from._internal_customproperties_value());
      break;
    }
    case CUSTOMPROPERTIES_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ParameterDefinitionProto::CopyFrom(const ParameterDefinitionProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Quix.Process.ParameterDefinitionProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParameterDefinitionProto::IsInitialized() const {
  return true;
}

void ParameterDefinitionProto::InternalSwap(ParameterDefinitionProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &id_, lhs_arena,
      &other->id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &location_, lhs_arena,
      &other->location_, rhs_arena
  );
  swap(name_, other->name_);
  swap(description_, other->description_);
  swap(minimumValue_, other->minimumValue_);
  swap(maximumValue_, other->maximumValue_);
  swap(unit_, other->unit_);
  swap(format_, other->format_);
  swap(customProperties_, other->customProperties_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  swap(_oneof_case_[1], other->_oneof_case_[1]);
  swap(_oneof_case_[2], other->_oneof_case_[2]);
  swap(_oneof_case_[3], other->_oneof_case_[3]);
  swap(_oneof_case_[4], other->_oneof_case_[4]);
  swap(_oneof_case_[5], other->_oneof_case_[5]);
  swap(_oneof_case_[6], other->_oneof_case_[6]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ParameterDefinitionProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_parameterDefinitionsProto_2eproto_getter, &descriptor_table_parameterDefinitionsProto_2eproto_once,
      file_level_metadata_parameterDefinitionsProto_2eproto[0]);
}

// ===================================================================

class ParameterDefinitionsProto::_Internal {
 public:
};

ParameterDefinitionsProto::ParameterDefinitionsProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  parameters_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:Quix.Process.ParameterDefinitionsProto)
}
ParameterDefinitionsProto::ParameterDefinitionsProto(const ParameterDefinitionsProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      parameters_(from.parameters_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Quix.Process.ParameterDefinitionsProto)
}

inline void ParameterDefinitionsProto::SharedCtor() {
}

ParameterDefinitionsProto::~ParameterDefinitionsProto() {
  // @@protoc_insertion_point(destructor:Quix.Process.ParameterDefinitionsProto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ParameterDefinitionsProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ParameterDefinitionsProto::ArenaDtor(void* object) {
  ParameterDefinitionsProto* _this = reinterpret_cast< ParameterDefinitionsProto* >(object);
  (void)_this;
}
void ParameterDefinitionsProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ParameterDefinitionsProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ParameterDefinitionsProto::Clear() {
// @@protoc_insertion_point(message_clear_start:Quix.Process.ParameterDefinitionsProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  parameters_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ParameterDefinitionsProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Quix.Process.ParameterDefinitionProto parameters = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_parameters(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ParameterDefinitionsProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Quix.Process.ParameterDefinitionsProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Quix.Process.ParameterDefinitionProto parameters = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_parameters_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_parameters(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Quix.Process.ParameterDefinitionsProto)
  return target;
}

size_t ParameterDefinitionsProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Quix.Process.ParameterDefinitionsProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Quix.Process.ParameterDefinitionProto parameters = 1;
  total_size += 1UL * this->_internal_parameters_size();
  for (const auto& msg : this->parameters_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ParameterDefinitionsProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ParameterDefinitionsProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ParameterDefinitionsProto::GetClassData() const { return &_class_data_; }

void ParameterDefinitionsProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ParameterDefinitionsProto *>(to)->MergeFrom(
      static_cast<const ParameterDefinitionsProto &>(from));
}


void ParameterDefinitionsProto::MergeFrom(const ParameterDefinitionsProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Quix.Process.ParameterDefinitionsProto)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  parameters_.MergeFrom(from.parameters_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ParameterDefinitionsProto::CopyFrom(const ParameterDefinitionsProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Quix.Process.ParameterDefinitionsProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParameterDefinitionsProto::IsInitialized() const {
  return true;
}

void ParameterDefinitionsProto::InternalSwap(ParameterDefinitionsProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  parameters_.InternalSwap(&other->parameters_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ParameterDefinitionsProto::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_parameterDefinitionsProto_2eproto_getter, &descriptor_table_parameterDefinitionsProto_2eproto_once,
      file_level_metadata_parameterDefinitionsProto_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Process
}  // namespace Quix
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Quix::Process::ParameterDefinitionProto* Arena::CreateMaybeMessage< ::Quix::Process::ParameterDefinitionProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Quix::Process::ParameterDefinitionProto >(arena);
}
template<> PROTOBUF_NOINLINE ::Quix::Process::ParameterDefinitionsProto* Arena::CreateMaybeMessage< ::Quix::Process::ParameterDefinitionsProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Quix::Process::ParameterDefinitionsProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
